home:
    path:     /
    defaults: { _controller: "SellermaniaTestBundle:Home:index" }
    methods:  GET

idea_list:
    path:     /idea/list
    defaults: { _controller: "SellermaniaTestBundle:Idea:index" }
    methods:  GET

show_idea:
    path:     /idea/{id}/show
    defaults: { _controller: "SellermaniaTestBundle:Idea:show" }
    methods:  GET

new_idea:
    path:     /idea/new
    defaults: { _controller: "SellermaniaTestBundle:Idea:new" }
    methods:  [GET, POST]

comment_new:
    path:     /idea/{id}/add_comment
    defaults: { _controller: "SellermaniaTestBundle:Comment:new" }
    methods:  [GET, POST]

vote_new:
    path:     /idea/{id}/add_vote/{value}
    defaults: { _controller: "SellermaniaTestBundle:Vote:new" }
    methods:  [GET, POST]

edit_idea:
    path:     /idea/{id}/edit
    defaults: { _controller: "SellermaniaTestBundle:Idea:edit" }
    methods:  [GET, POST]

delete_idea:
    path:     /idea/{id}/delete
    defaults: { _controller: "SellermaniaTestBundle:Idea:delete" }
    methods:  DELETE